config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 120 }
  validates :body, presence: true, length: { minimum: 3 }
  validates :user_id, presence: true

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,  uniqueness: { case_sensitive: false},
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false}, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:warning] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except:[:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order('created_at desc').paginate(page: params[:page])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article was successfully created.'
      redirect_to article_path(@article)
    else
      render 'new'
    end

  end

  def show

  end

  def edit

  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated.'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:warning] = 'Article was successfully deleted.'
    redirect_to articles_path
  end


  private

    def article_params
      params.require(:article).permit(:title, :body, category_ids: [])
    end

    def find_article
      @article = Article.find(params[:id])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = 'You can only edit or delete your own articles.'
        redirect_to root_path
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:index, :show]


  def index
    @categories = Category.order('name').paginate(page: params[:page], per_page: 10)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category created successfully'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:success] = 'Category name was successfully updated'
      redirect_to category_path(@category)
    else
      render 'edit'
    end

  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find(params[:id])
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:warning] = 'Only admins can perform that action.'
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in.'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Login failed, please check your username/password.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out.'
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.all.order('username').paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to NoobBlog #{@user.username}!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Account successfully updated'
      redirect_to articles_path
    else
      render 'edit'
    end

  end

  def show
    @user_articles = @user.articles.order('created_at desc').paginate(page: params[:page])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = 'User and all articles created by user have been deleted.'
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = 'You can only edit your own account.'
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = 'Only admin users can perform that action'
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options= { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="article-list ">
  <% obj.each do |article| %>
      <div class="article">
        <h2><%= link_to article.title, article_path(article) %></h2>
        <div class="meta">Posted by: <span><%= article.user.username %></span> <span><%= time_ago_in_words(article.created_at) %> ago</span>.</div>
        <div class="summary">
          <%= truncate(article.body, escape: false, length: 100 ) %>
        </div>
        <% if article.categories.any? %>
            <div class="meta category">Categories:
              <%= render article.categories %>
            </div>
        <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin? )%>
        <div class="actions">
          <%= link_to 'Edit', edit_article_path(article), :class => 'btn-xs btn-info' %>
          <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn-xs btn-danger' %>
        </div>
        <% end %>
      </div>
      <hr />
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= simple_form_for @article do |f| %>

      <%= f.input :title %>
      <%= f.input :body %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
      <br />
      <%= f.submit 'Submit', :class => 'btn btn-success' %>
      <%= link_to 'Cancel', articles_path, :class => 'btn btn-default' %>

<% end %>

app/views/articles/edit.html.erb
<div class="container">
<div class="page-header">
  <h1>Edit <%= @article.title %></h1>
</div>
<%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
<div class="row">
<div class="col-md-12">
  <div class="page-header">
    <h1>All Articles</h1>
  </div>
  <%= render 'article', obj: @articles %>
  <div class="center">
    <%= will_paginate %>
  </div>
</div>

</div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="page-header center">
    <h1>New Article</h1>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="page-header">
    <h1><%= @article.title %></h1>
  </div>
  <div class="meta">Posted by: <span><%= link_to @article.user.username, user_path(@article.user), :class => 'username' %></span> on <%= @article.created_at.to_s(:long) %></div>
  <% if @article.categories.any? %>
    <div class="meta category">Categories:
      <%= render @article.categories %>
    </div>
  <% end %>
  <div><%= simple_format(@article.body) %></div>
  <div class="meta"><span>Last updated: <%= time_ago_in_words(@article.created_at) %> ago </span></div>
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
  <%= link_to 'Edit', edit_article_path, :class => 'btn btn-info' %>
  <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: 'Are you sure you want to delete this article?'}, :class => 'btn btn-danger' %>
  <%= link_to 'Back', articles_path, :class => 'btn btn-default' %>
  <% end %>
</div>

app/views/categories/_category.html.erb
<%= link_to "#{category.name}", category_path(category) %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= simple_form_for @category do |f| %>

    <%= f.input :name, placeholder: 'Category Name' %>
    <%= f.submit 'Submit', :class => 'btn btn-success' %>
    <%= link_to 'Cancel', categories_path, :class => 'btn btn-default' %>

<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="page-header center">
    <h1>Edit Category: <%= @category.name %></h1>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1>All Categories</h1>
      </div>
      <% @categories.each do |category| %>
        <div>
          <%= link_to "#{category.name}", category_path(category) %> - <small><%= pluralize(category.articles.count, "article") %></small>
        </div>
      <% end %>

      <div class="center">
        <%= will_paginate %>
      </div>
    </div>

  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="page-header center">
    <h1>New Category</h1>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="page-header">
    <h1>Category: <%= @category.name %></h1>
    <% if logged_in? && current_user.admin? %>
      <%= link_to 'Edit Category Name', edit_category_path(@category), :class => 'btn-xs btn-default' %>
    <% end %>
  </div>
  <div class="col-md-12">
    <%= render 'articles/article', obj: @category_articles %>
    <div class="center">
      <%= will_paginate @category_articles %>
    </div>
  </div>

</div>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <p class="center">&copy2016 Noobita.</p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div id="flash-messages"class="container">
  <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %> alert-dismissible' role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= msg %>
      </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mobile-menu ">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">noobita</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="mobile-menu">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Articles', articles_path %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories  <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if logged_in? and current_user.admin? %>
                <li>
                  <%= link_to 'Add Category', new_category_path %>
                </li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to 'All Categories', categories_path %>
            </li>
            <% Category.all.each do |category| %>
            <li>
              <%= link_to "#{category.name}" , category_path(category) %>
            </li>
            <% end %>
          </ul>

        </li>
        <li>
          <%= link_to 'Users', users_path %>
        </li>
        <li>
          <%= link_to 'About', about_path %>
        </li>

        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Profile <%= 'Admin' if current_user.admin? %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Edit Profile', edit_user_path(current_user) %>
                </li>
                <li>
                  <%= link_to 'View Profile', user_path(current_user) %>
                </li>
                <li>
                  <%= link_to 'New Article', new_article_path %>
                </li>
                <li>
                  <%= link_to 'Log out', logout_path, method: :delete %>
                </li>
              </ul>
            </li>


        <% else %>
            <li>
              <%= link_to 'Log in', login_path %>
            </li>
            <li>
              <%= link_to 'Sign Up', signup_path %>
            </li>

        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoobBlog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="page-header">
    <h1>About</h1>
  </div>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec maximus nibh, ac lobortis nisl. Mauris lorem nunc, egestas ac ipsum et, auctor lacinia enim. Sed pulvinar auctor neque, ac mollis metus interdum eget. Donec fringilla finibus metus, id aliquet purus accumsan sit amet. Aliquam ullamcorper pharetra leo nec viverra. Aliquam tincidunt maximus lacus, id ornare neque sollicitudin et. Aliquam lectus mi, aliquam ut pretium id, faucibus non enim.</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container center">
    <h1>Welcome to NoobBlog</h1>
    <p>Rails Blog<p>
      <%= link_to 'Sign Up', signup_path, :class => 'btn btn-success btn-lg' %>
    </p>
  </div>
</div>
<div class="container">
  <div class="col-md-6">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec maximus nibh, ac lobortis nisl. Mauris lorem nunc, egestas ac ipsum et, auctor lacinia enim. Sed pulvinar auctor neque, ac mollis metus interdum eget. Donec fringilla finibus metus, id aliquet purus accumsan sit amet. Aliquam ullamcorper pharetra leo nec viverra. Aliquam tincidunt maximus lacus, id ornare neque sollicitudin et. Aliquam lectus mi, aliquam ut pretium id, faucibus non enim.</p>
  </div>
  <div class="col-md-6">
    <p>Fusce at ligula massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur a leo tempus, sagittis odio sit amet, auctor leo. Mauris eget varius neque. Nulla nec augue tempus, tempor purus vel, blandit lectus. Cras ultricies condimentum orci, quis fringilla arcu viverra vel. Aliquam eleifend congue bibendum.</p>
  </div>
  <div class="col-md-12">
    <p>Proin finibus quis ex vel varius. In ut sem blandit justo varius auctor. Cras venenatis cursus mattis. Praesent eget justo purus. Maecenas elementum dolor ligula, in convallis metus ultrices vel. Donec aliquam efficitur massa at maximus. Ut eget hendrerit ante, sodales lacinia elit. Integer at leo est. Phasellus posuere at purus at convallis. Sed feugiat lacus volutpat sapien dapibus fringilla. Nullam congue eget massa varius luctus. Maecenas dignissim nibh eget sapien ornare, et finibus velit iaculis.</p>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= msg %>
        </div>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= simple_form_for @user do |f| %>

    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.submit(@user.new_record? ? 'Sign Up' : 'Update', :class => 'btn btn-success' ) %>
    <%= link_to 'Cancel', articles_path, :class => 'btn btn-default' %>

<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit Account</h1>
  </div>

  <%= render 'form' %>

</div>

app/views/users/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>All Users</h1>
  </div>
    <div class="users-list">
      <% @users.each do |user| %>
      <div class="user">
        <%= link_to gravatar_for(user, size: 48), user_path(user), :class => 'gravatar' %>
        <p class="username"><%= link_to user.username, user_path(user) %></p>
        <%= pluralize(user.articles.count, 'article') if user.articles %>
        <% if logged_in? and current_user.admin? %>
         <div><%= link_to 'Delete User', user_path(user), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn-sm btn-danger'  %> </div>
      <% end %>
      </div>
          <hr >
        <% end %>
    </div>

  <div class="center">
    <%= will_paginate %>
  </div>

</div>

app/views/users/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>Signup</h1>
  </div>

  <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= msg %>
          </div>
      <% end %>
  <% end %>

  <%= simple_form_for @user do |f| %>

      <%= f.input :username %>
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.submit 'Sign Up', :class => 'btn btn-success' %>
      <%= link_to 'Cancel', articles_path, :class => 'btn btn-default' %>

  <% end %>

</div>

app/views/users/show.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="center"><%= @user.username%>'s Profile</h1>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
      <%= gravatar_for @user, size: 120 %>
    </div>
  </div>
    <hr />
  <div class="row">
    <div class="col-md-12">
    <h4 class="center"><%= pluralize(@user.articles.count, 'article') if @user.articles %></h4>
      <%= render 'articles/article', obj: @user_articles %>
      <div class="center">
        <%= will_paginate @user_articles %>
      </div>
    </div>
  </div>


</div>